Traceback (most recent call last):
  File "/home/thomas/Projects/Virtual_Few_Shot/vibelab-2/llm_backend.py", line 402, in <module>
    main()
    ~~~~^^
  File "/home/thomas/Projects/Virtual_Few_Shot/vibelab-2/llm_backend.py", line 391, in main
    server = HTTPServer(('localhost', port), EnhancedVibeLab)
  File "/usr/lib/python3.13/socketserver.py", line 457, in __init__
    self.server_bind()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 98] Address already in use
